"""add servers and related tables

Revision ID: 34c627bb77e0
Revises: 3b31a4298e82
Create Date: 2026-03-28 23:31:52.683918

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '34c627bb77e0'
down_revision: Union[str, None] = '3b31a4298e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###