"""add home_score away_score to matches

Revision ID: 48b930667d4d
Revises: e466cf740f20
Create Date: 2026-03-16 20:32:04.858524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b930667d4d'
down_revision: Union[str, None] = 'e466cf740f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('away_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'away_score')
    op.drop_column('matches', 'home_score')
    # ### end Alembic commands ###
