"""add join requests accept decline

Revision ID: 543aca7a692b
Revises: 4d8a5c9e2f1b
Create Date: 2026-04-25 15:04:39.457201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543aca7a692b'
down_revision: Union[str, None] = '4d8a5c9e2f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_google_tokens_user_id', table_name='google_tokens', if_exists=True)
    op.create_index(op.f('ix_server_join_requests_id'), 'server_join_requests', ['id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_join_requests_id'), table_name='server_join_requests')
    op.create_index('ix_google_tokens_user_id', 'google_tokens', ['user_id'], unique=False)
    op.alter_column('calendar_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
