"""add server is_public and join requests

Revision ID: 7ccbd1e7e416
Revises: 3b31a4298e82
Create Date: 2026-03-28 22:58:51.069069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccbd1e7e416'
down_revision: Union[str, None] = '3b31a4298e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
