FROM node:20-alpine

WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install

# copy project
COPY . .

# build vite app
RUN npm run build

# install static server
RUN npm install -g serve

# railway port
EXPOSE 5173

# start server
CMD ["sh", "-c", "serve -s dist -l $PORT"]