[loggers]
keys=root,sqlalchemy.engine,httpx,httpcore,uvicorn.access

[handlers]
keys=console

[formatters]
keys=default

[logger_root]
level=DEBUG
handlers=console

[logger_sqlalchemy.engine]
level=WARNING
handlers=
qualname=sqlalchemy.engine
propagate=0

[logger_httpx]
level=WARNING
handlers=
qualname=httpx
propagate=1

[logger_httpcore]
level=WARNING
handlers=
qualname=httpcore
propagate=1

[logger_uvicorn.access]
level=WARNING
handlers=
qualname=uvicorn.access
propagate=1

[handler_console]
class=StreamHandler
formatter=default
args=(sys.stdout,)

[formatter_default]
format=%(asctime)s | %(levelname)-8s | %(name)s | %(message)s
datefmt=%Y-%m-%d %H:%M:%S